#Cumulative details table
DROP TABLE IF EXISTS `statmod`.`offer_outcome_details`;

CREATE TABLE `statmod`.`offer_outcome_details` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `property_id` int(11) NOT NULL,
    `ext_booking_id` varchar(40) COLLATE utf8_unicode_ci NOT NULL COMMENT 'pcd',
    `arrival` date NOT NULL COMMENT 'gad',
    `pet` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'pet',
    `cumulative_exposures` int(11) unsigned NOT NULL default 0,
    `cumulative_interests` int(11) unsigned NOT NULL default 0,
    `cumulative_requests` int(11) unsigned NOT NULL default 0,
    `cumulative_awards` int(11) unsigned NOT NULL default 0,
    `last_exposure_interested` tinyint(1) default NULL COMMENT '1 = yes, 0 = no',
    `last_interest_committed` tinyint(1) default NULL COMMENT '1 = yes, 0 = no',
    `last_request_awarded` tinyint(1) default NULL COMMENT '1 = yes, 0 = no',
    `last_exposure_datetime` datetime default NULL,
    `last_interest_datetime` datetime default NULL,
    `last_committed_datetime` datetime default NULL,
    `last_awarded_date` date default NULL,
    `max_committed_spend_absolute` float(10,2) default NULL,
    `max_awarded_spend_absolute` float(10,2) default NULL,
    `loyalty_history` tinyint(1) default NULL COMMENT '1 = yes, 0 = no',
    `multiple_associated_names` tinyint(1) NOT NULL default 0 COMMENT '1 = yes, 0 = no',
    `cancelled` tinyint(1) NOT NULL default 0 COMMENT '0 = not cancelled, 1 = upgrade cancelled, 2 = booking cancelled',
    `toro_interested_flag` tinyint(1) DEFAULT '0' COMMENT '1 = toro interested, 0 = not toro interested',
    `toro_committed_flag` tinyint(1) DEFAULT '0' COMMENT '1 = toro committed, 0 = not toro committed',
    `toro_awarded_flag` tinyint(1) DEFAULT '0' COMMENT '1 = toro awarded, 0 = not toro awarded',
    `upgrade_matrix_id` int(11) NOT NULL,
    `from_category_code` varchar(20) NOT NULL COMMENT 'rcc',
    `from_category_id` int(11) NOT NULL,
    `to_category_id` int(11) NOT NULL,
    `from_category_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
    `to_category_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
    `from_room_size` int(11) unsigned default NULL,
    `to_room_size` int(11) unsigned default NULL,
    `upg_price` float(10,2) NOT NULL,
    `from_price` float(10,2) NOT NULL,
    `to_price` float(10,2) NOT NULL,
    `to_type` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
    `committed` tinyint(1) DEFAULT '0' COMMENT '1 = committed, 0 = not committed',
    `awarded` tinyint(1) DEFAULT '0' COMMENT '1 = awarded, 0 = not awarded',
    `upg_total_revenue` float(10,2) DEFAULT '0.00',
    `total_booking_price` float(10,2) NOT NULL COMMENT 'tbp',
    `length_of_stay` smallint(3) default NULL COMMENT 'nmn',
    `first_name` varchar(100) default NULL COMMENT 'gfn',
    `email` varchar(100) default NULL COMMENT 'gem',
    `domain` varchar(100) default NULL,
    `adult_count` tinyint(1) default NULL COMMENT 'noa',
    `child_count` tinyint(1) default NULL COMMENT 'noc',
    `room_count` tinyint(3) NOT NULL COMMENT 'gnr',
    `language` varchar(2) NOT NULL COMMENT 'lng',
    `loyalty` varchar(3) NOT NULL COMMENT 'plc',
    `rate_code` varchar(12) default NULL COMMENT 'srp',
    `rate_tier` varchar(12) default NULL COMMENT 'prt',
    `offer_set_size` tinyint(1) default NULL,
    `property_booking_date` datetime default NULL COMMENT 'pts',
    `exposure_timestamp` datetime NOT NULL COMMENT 'created field in lmi table',
    `modified` datetime NULL default '0000-00-00 00:00:00',
    `modified_after_id` int(11) NOT NULL default 0,
    `created` timestamp NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `upgrade_item` (`property_id`,`ext_booking_id`,`arrival`,`pet`,`to_category_id`),
    KEY `touchpoint` (`property_id`,`ext_booking_id`,`arrival`,`pet`),
    KEY `booking` (`property_id`,`ext_booking_id`,`arrival`),
    KEY `mad` (`modified_after_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;