#summary from offer_outcome_details
SET @max_id = (SELECT max(`modified_after_id`) FROM `statmod`.`offer_outcome_details`);

DROP TABLE IF EXISTS `statmod`.`offer_outcome_details_sum_temp`;

CREATE TABLE `statmod`.`offer_outcome_details_sum_temp` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `property_id` int(11) NOT NULL,
    `ext_booking_id` varchar(40) COLLATE utf8_unicode_ci NOT NULL COMMENT 'pcd',
    `arrival` date NOT NULL COMMENT 'gad',
    `pet` varchar(5) COLLATE utf8_unicode_ci NOT NULL COMMENT 'pet',
    `from_room_size` int(11) unsigned default NULL,
    `cumulative_exposures` int(11) unsigned NOT NULL default 0,
    `cumulative_interests` int(11) unsigned NOT NULL default 0,
    `cumulative_requests` int(11) unsigned NOT NULL default 0,
    `cumulative_awards` int(11) unsigned NOT NULL default 0,
    `last_exposure_interested` tinyint(1) default NULL COMMENT '1 = yes, 0 = no',
    `last_interest_committed` tinyint(1) default NULL COMMENT '1 = yes, 0 = no',
    `last_request_awarded` tinyint(1) default NULL COMMENT '1 = yes, 0 = no',
    `last_exposure_datetime` datetime default NULL,
    `last_interest_datetime` datetime default NULL,
    `last_committed_datetime` datetime default NULL,
    `last_awarded_date` date default NULL,
    `max_committed_spend_absolute` float(10,2) default NULL,
    `max_awarded_spend_absolute` float(10,2) default NULL,
    `loyalty_history` tinyint(1) default NULL COMMENT '1 = yes, 0 = no',
    `multiple_associated_names` tinyint(1) NOT NULL default 0 COMMENT '1 = yes, 0 = no',
    `x_cancelled` tinyint(1) NOT NULL default 0 COMMENT '0 = not cancelled, 1 = upgrade cancelled, 2 = booking cancelled',
    `x_toro_interested_flag` tinyint(1) default 0 COMMENT '1 = toro interested, 0 = not toro interested',
    `x_toro_committed_flag` tinyint(1) default 0 COMMENT '1 = toro committed, 0 = not toro committed',
    `x_toro_awarded_flag` tinyint(1) default 0 COMMENT '1 = toro awarded, 0 = not toro awarded',
    `x_interested` tinyint(1) NOT NULL default 0 COMMENT '1 = interested, 0 = not interested',
    `x_committed` tinyint(1) NOT NULL default 0 COMMENT '1 = committed, 0 = not committed',
    `request_count` tinyint(1) NOT NULL default 0 COMMENT 'integer count of requested items',
    `x_awarded` tinyint(1) default 0 COMMENT '1 = awarded, 0 = not awarded',
    `max_request_price` float(10,2) default NULL,
    `total_potential_revenue_addon` float(10,2) NOT NULL default 0 COMMENT 'sum of revenue from requested add-ons',
    `total_potential_revenue_upgrade` float(10,2) NOT NULL default 0 COMMENT 'max of revenue from requested add-ons',
    `total_awarded_revenue_addon` float(10,2) NOT NULL default 0,
    `total_awarded_revenue_upgrade` float(10,2) NOT NULL default 0,
    `created` timestamp NULL default CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `touchpoint` (`property_id`,`ext_booking_id`,`arrival`,`pet`),
    KEY `booking` (`property_id`,`ext_booking_id`,`arrival`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `statmod`.`offer_outcome_details_sum_temp` (
    `property_id`,
    `ext_booking_id`,
    `arrival`,
    `pet`,
    `from_room_size`,
    #begin guest history features
    `cumulative_exposures`,
    `cumulative_interests`,
    `cumulative_requests`,
    `cumulative_awards`,
    `last_exposure_interested`,
    `last_interest_committed`,
    `last_request_awarded`,
    `last_exposure_datetime`,
    `last_interest_datetime`,
    `last_committed_datetime`,
    `last_awarded_date`,
    `max_committed_spend_absolute`,
    `max_awarded_spend_absolute`,
    `loyalty_history`,
    `multiple_associated_names`,
    #end guest history features
    `x_cancelled`,
    `x_toro_interested_flag`,
    `x_toro_committed_flag`,
    `x_toro_awarded_flag`,
    `x_interested`,
    `x_committed`,
    `request_count`,
    `x_awarded`,
    `max_request_price`,
    `total_potential_revenue_addon`,
    `total_potential_revenue_upgrade`,
    `total_awarded_revenue_addon`,
    `total_awarded_revenue_upgrade`
) SELECT 
    `o`.`property_id`,
    `o`.`ext_booking_id`,
    `o`.`arrival`,
    `o`.`pet`,
    `o`.`from_room_size`,
    #begin guest history features
    `o`.`cumulative_exposures`,
    `o`.`cumulative_interests`,
    `o`.`cumulative_requests`,
    `o`.`cumulative_awards`,
    `o`.`last_exposure_interested`,
    `o`.`last_interest_committed`,
    `o`.`last_request_awarded`,
    `o`.`last_exposure_datetime`,
    `o`.`last_interest_datetime`,
    `o`.`last_committed_datetime`,
    `o`.`last_awarded_date`,
    `o`.`max_committed_spend_absolute`,
    `o`.`max_awarded_spend_absolute`,
    `o`.`loyalty_history`,
    `o`.`multiple_associated_names`,
    #end guest history features
    `o`.`cancelled`,
    `o`.`toro_interested_flag`,
    `o`.`toro_committed_flag`,
    `o`.`toro_awarded_flag`,
    1, #`o`.`interested`,
    `o`.`committed`,
    `o`.`committed`, #`o`.`request_count`,
    `o`.`awarded`,
    `o`.`upg_price`, #`o`.`max_request_price`,
    if(`o`.`to_type`='room_upgrade',0,`o`.`upg_total_revenue`), #`o`.`total_potential_revenue_addon`,
    if(`o`.`to_type`='room_upgrade',`o`.`upg_total_revenue`,0), #`o`.`total_potential_revenue_upgrade`,
    `o`.`awarded`*if(`o`.`to_type`='room_upgrade',0,`o`.`upg_total_revenue`), #`o`.`total_awarded_revenue_addon`,
    `o`.`awarded`*if(`o`.`to_type`='room_upgrade',`o`.`upg_total_revenue`,0) #`o`.`total_awarded_revenue_upgrade`,
FROM `statmod`.`offer_outcome_details` AS `o`
WHERE `modified_after_id` = @max_id
ON DUPLICATE KEY UPDATE
    `x_cancelled` = `o`.`cancelled`,
    `x_toro_interested_flag` = if(`o`.`toro_interested_flag` = 1, 1, `x_toro_interested_flag`),
    `x_toro_committed_flag` = if(`o`.`toro_committed_flag` = 1, 1, `x_toro_committed_flag`),
    `x_toro_awarded_flag` = if(`o`.`toro_awarded_flag` = 1, 1, `x_toro_awarded_flag`),
    `x_committed` = if(`o`.`committed` = 1, 1, `x_committed`),
    `x_awarded` = if(`o`.`awarded` = 1, 1, `x_awarded`),
    `request_count` = `request_count` + `o`.`committed`,
    `max_request_price` = if(`max_request_price` < `o`.`upg_price`, `o`.`upg_price`, `max_request_price`),
    `total_potential_revenue_addon` = `total_potential_revenue_addon` + if(`o`.`to_type`='room_upgrade',0,`o`.`upg_total_revenue`),
    `total_potential_revenue_upgrade` = if(`total_potential_revenue_upgrade` < if(`o`.`to_type`='room_upgrade',`o`.`upg_total_revenue`,0), if(`o`.`to_type`='room_upgrade',`o`.`upg_total_revenue`,0), `total_potential_revenue_upgrade`),
    `total_awarded_revenue_addon` = `total_awarded_revenue_addon` + `o`.`awarded`*if(`o`.`to_type`='room_upgrade',0,`o`.`upg_total_revenue`),
    `total_awarded_revenue_upgrade` = `total_awarded_revenue_upgrade` + `o`.`awarded`*if(`o`.`to_type`='room_upgrade',`o`.`upg_total_revenue`,0)
;

#insert new exposures
INSERT IGNORE `statmod`.`offer_outcome_summary` (
    `property_id`,
    `ext_booking_id`,
    `arrival`,
    `pet`,
    `from_room_size`,
    #begin guest history features
    `cumulative_exposures`,
    `cumulative_interests`,
    `cumulative_requests`,
    `cumulative_awards`,
    `last_exposure_interested`,
    `last_interest_committed`,
    `last_request_awarded`,
    `last_exposure_datetime`,
    `last_interest_datetime`,
    `last_committed_datetime`,
    `last_awarded_date`,
    `max_committed_spend_absolute`,
    `max_awarded_spend_absolute`,
    `loyalty_history`,
    `multiple_associated_names`,
    #end guest history features
    #`cancelled`,
    `toro_exposed_flag`,
    #`toro_interested_flag`,
    #`toro_committed_flag`,
    #`toro_awarded_flag`,
    #`interested`,
    #`committed`,
    #`request_count`,
    #`awarded`,
    `upgrade_matrix_id`,
    `from_category_name`,
    `from_category_code`,
    `from_category_id`,
    `from_price`,
    #`max_request_price`,
    #`total_potential_revenue_addon`,
    #`total_potential_revenue_upgrade`,
    #`total_awarded_revenue_addon`,
    #`total_awarded_revenue_upgrade`,
    `matrix_lmi_price`,
    `toro_lmi_price`,
    `total_booking_price`,
    `length_of_stay`,
    `first_name`,
    `email`,
    `domain`,
    `adult_count`,
    `child_count`,
    `room_count`,
    `language`,
    `loyalty`,
    `rate_code`,
    `rate_tier`,
    `property_booking_date`,
    `exposure_timestamp`
) SELECT 
    `e`.`property_id`,
    `e`.`ext_booking_id`,
    `e`.`arrival`,
    `e`.`pet`,
    `e`.`from_room_size`,
    #begin guest history features
    `e`.`cumulative_exposures`,
    `e`.`cumulative_interests`,
    `e`.`cumulative_requests`,
    `e`.`cumulative_awards`,
    `e`.`last_exposure_interested`,
    `e`.`last_interest_committed`,
    `e`.`last_request_awarded`,
    `e`.`last_exposure_datetime`,
    `e`.`last_interest_datetime`,
    `e`.`last_committed_datetime`,
    `e`.`last_awarded_date`,
    `e`.`max_committed_spend_absolute`,
    `e`.`max_awarded_spend_absolute`,
    `e`.`loyalty_history`,
    `e`.`multiple_associated_names`,
    #end guest history features
    #`cancelled`,
    `e`.`toro_exposed_flag`,
    #`toro_interested_flag`,
    #`toro_committed_flag`,
    #`toro_awarded_flag`,
    #`cancelled`,
    #`interested`,
    #`committed`,
    #`request_count`,
    #`awarded`,
    `e`.`upgrade_matrix_id`,
    `e`.`from_category_name`,
    `e`.`from_category_code`,
    `e`.`from_category_id`,
    `e`.`total_booking_price`/`e`.`length_of_stay`, #from_price
    #`max_request_price`,
    #`total_potential_revenue_addon`,
    #`total_potential_revenue_upgrade`,
    #`total_awarded_revenue_addon`,
    #`total_awarded_revenue_upgrade`,
    `e`.`matrix_lmi_price`,
    `e`.`toro_lmi_price`,
    `e`.`total_booking_price`,
    `e`.`length_of_stay`,
    `e`.`first_name`,
    `e`.`email`,
    `e`.`domain`,
    `e`.`adult_count`,
    `e`.`child_count`,
    `e`.`room_count`,
    `e`.`language`,
    `e`.`loyalty`,
    `e`.`rate_code`,
    `e`.`rate_tier`,
    `e`.`property_booking_date`,
    `e`.`exposure_timestamp`
FROM `statmod`.`exposed` AS `e`;

#update outcomes from details summary temp table
UPDATE `statmod`.`offer_outcome_summary` AS `s` 
LEFT JOIN `statmod`.`offer_outcome_details_sum_temp` AS `d`
    ON `s`.`property_id` = `d`.`property_id`
    AND `s`.`ext_booking_id` = `d`.`ext_booking_id`
    AND `s`.`arrival` = `d`.`arrival`
    AND `s`.`pet` = `d`.`pet`
SET `s`.`toro_interested_flag` = `d`.`x_toro_interested_flag`,
    `s`.`toro_committed_flag` = `d`.`x_toro_committed_flag`,
    `s`.`toro_awarded_flag` = `d`.`x_toro_awarded_flag`,
    `s`.`cancelled` = `d`.`x_cancelled`,
    `s`.`interested` = `d`.`x_interested`,
    `s`.`committed` = `d`.`x_committed`,
    `s`.`request_count` = `d`.`request_count`,
    `s`.`awarded` = `d`.`x_awarded`,
    `s`.`max_request_price` = `d`.`max_request_price`,
    `s`.`total_potential_revenue_addon` = `d`.`total_potential_revenue_addon`,
    `s`.`total_potential_revenue_upgrade` = `d`.`total_potential_revenue_upgrade`,
    `s`.`total_awarded_revenue_addon` = `d`.`total_awarded_revenue_addon`,
    `s`.`total_awarded_revenue_upgrade` = `d`.`total_awarded_revenue_upgrade`
WHERE `s`.`property_id` = `d`.`property_id`
    AND `s`.`ext_booking_id` = `d`.`ext_booking_id`
    AND `s`.`arrival` = `d`.`arrival`
    AND `s`.`pet` = `d`.`pet`
;
    
DROP TABLE IF EXISTS `statmod`.`offer_outcome_details_sum_temp`;